plays = 3.0
last = "2026-09-07"
weight = 1.0

[tops."In This Hole"]
liked = true

[tops."Metal Heart"]
plays = 1.0
last = "2026-09-07"

[tops."Nude As the News"]
liked = true

[tops."Sea of Love"]
plays = 1.0
last = "2026-09-07"

[tops."The Greatest"]
plays = 1.0
last = "2026-09-07"
