plays = 3.0
last = "2026-09-06"
weight = 1.0

[tops."Je veux te baiser"]
plays = 1.0
last = "2026-09-06"

[tops.Vilaine]
plays = 1.0
last = "2026-09-06"

[tops.Novembre]
plays = 1.0
last = "2026-09-06"
